<h1>Multiple Linear Regression</h1>


<h2>Objective</h2><ul><li> How to make the prediction for multiple inputs.</li><li> How to use linear class to build more complex models.</li><li> How to build a custom module.</li></ul> 


<h2>Table of Contents</h2>
<p>In this lab, you will review how to make a prediction in several different ways by using PyTorch.</p>

 <div>
        1. <a href="#Prediction">Prediction</a><br>
        2. <a href="#Class-Linear">Class Linear</a><br>
        3. <a href="#Build-Custom-Modules">Build Custom Modules</a>
    </div>

<h2>Preparation</h2>


Import the libraries and set the random seed.


In [1]:
from torch import nn
import torch
torch.manual_seed(1)

<h2 id="Prediction">Prediction</h2>


Set weight and bias.


In [2]:
w = torch.tensor([[2.0], [3.0]], requires_grad=True)
b = torch.tensor([[1.0]], requires_grad=True)

Define the parameters. <code>torch.mm</code> uses matrix multiplication instead of scaler multiplication.


In [4]:
def forward(x):
    return torch.mm(x, w) + b

The function <code>forward</code> implements the following equation:


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1_matrix_eq.png" width="600" alt="Matrix Linear Regression">


If we input a <i>1x2</i> tensor, because we have a <i>2x1</i> tensor as <code>w</code>, we will get a <i>1x1</i> tensor: 


In [5]:
x = torch.tensor([[1.0, 2.0]])
yhat = forward(x)
print("The result: ", yhat)

The result:  tensor([[9.]], grad_fn=<AddBackward0>)


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/JBkvPoMCCa-PDXCF_4aQfQ/image%20-1-.png" width="300" alt="Linear Regression Matrix Sample One">


# Each row of the following tensor represents a sample:


In [8]:
X = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])

In [9]:
yhat = forward(X)
print("The result: ", yhat)

The result:  tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


## Class Linear


We can use the linear class to make a prediction. You'll also use the linear class to build more complex models.


Let us create a model.


In [10]:
model = nn.Linear(2, 1)

Make a prediction with the first sample:


In [11]:
yhat = model(x)
print("The result: ", yhat)

The result:  tensor([[-0.3969]], grad_fn=<AddmmBackward0>)


Predict with multiple samples <code>X</code>: 


In [12]:
yhat = model(X)
print("The result: ", yhat)

The result:  tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward0>)


The function performs matrix multiplication as shown in this image:


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1multi_sample_example.png" width="600" alt="Linear Regression Matrix Sample One">


## Build Custom Modules


Now, you'll build a custom module. You can make more complex models by using this method later. 


In [13]:
class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        return self.linear(x)

Build a linear regression object. The input feature size is two. 


In [14]:
model = LinearRegression(2, 1)

This will input the following equation:


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1_matrix_eq.png" width="600" alt="Matrix Linear Regression">


You can see the randomly initialized parameters by using the <code>parameters()</code> method:


In [15]:
print("The parameters: ", list(model.parameters()))

The parameters:  [Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]


You can also see the parameters by using the <code>state_dict()</code> method:


In [16]:
print("The parameters: ", model.state_dict())

The parameters:  OrderedDict([('linear.weight', tensor([[ 0.3319, -0.6657]])), ('linear.bias', tensor([0.4241]))])


Now we input a 1x2 tensor, and we will get a 1x1 tensor.


In [17]:
yhat = model(x)
print("The result: ", yhat)

The result:  tensor([[-0.5754]], grad_fn=<AddmmBackward0>)


The shape of the output is shown in the following image: 


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1_matrix_eq.png" width="600" alt="Matrix Linear Regression">


Make a prediction for multiple samples:


In [18]:
yhat = model(X)
print("The result: ", yhat)

The result:  tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward0>)


The shape is shown in the following image: 


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1Multi_sample.png" width="600" alt="Multiple Samples Linear Regression">


<h3>Practice</h3>


Build a model or object of type <code>linear_regression</code>. Using the <code>linear_regression</code> object will predict the following tensor: 


In [22]:
linear_regression = LinearRegression(4, 1)
X = torch.tensor([[11.0, 12.0, 13, 14], [11, 12, 13, 14]])

linear_regression(X)

tensor([[0.4101],
        [0.4101]], grad_fn=<AddmmBackward0>)